### ISSUE TITLE
Ratelimit error when looking up stats.

### ISSUE THREAD

**Issue by DonJTru** [VALTracker/VALTracker_desktop#4]
as title says:

```css
[///// API ERROR /////]

API: https://api.henrikdev.xyz/valorant/v3/matches/na/Annabxlla/Fmboy
Error Code: 429 (Rate limit exceeded,
 please try again later.)

Time of Error: 20.3.2022, 8:56:47 PM
```

**Comment by DonJTru** [comment]
the api endpoint (api.henrikdev.xyz) is returning this:
"Riot Origin Server Rate Limit, try again later"

**Comment by SpiritLetsPlays** [comment]
Hey,
Thanks for reporting this. You'll just have to wait a minute or two for the rate limit to get refreshed, then VALTracker will work as intended.

**Comment by DonJTru** [comment]
I tried to use it, I waited around an hour and still got the same issue.
Just now after hour and a half it's working.

**Comment by SpiritLetsPlays** [comment]
Glad it's working now.
The reason as to why this is happening is that VALTracker uses a public API to fetch player data (which will be changed sometime in the future), and this public API has a rate limit to Riot's Origin Servers. I'm powerless here for now, sorry.
